spring.application.name=api

# Configuração da ligação ao PostgreSQL e ao banco nexo_db
spring.datasource.url=jdbc:postgresql://localhost:5432/nexo_db
spring.datasource.username=postgres
spring.datasource.password=Bielssz7@

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true