spring.application.name=api

# URL do Supabase adaptada para o Java (via Session Pooler IPv4)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.aywlhxvljukjsmcspplc
# Substitua o texto abaixo pela senha real que você criou no Supabase:
spring.datasource.password=8aTF1lg7yUH3skLe

# Configurações do Hibernate para sincronizar a tabela na nuvem
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Configurações do Brevo (API HTTP) para envio de E-mails
brevo.api.key=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
brevo.email.remetente=gabrielsamtossouza.50@gmail.com
