spring.application.name=api

# URL do Supabase adaptada para o Java (com jdbc: no início)
spring.datasource.url=jdbc:postgresql://db.aywlhxvljukjsmcspplc.supabase.co:5432/postgres
spring.datasource.username=postgres
# Substitua o texto abaixo pela senha real que você criou no Supabase:
spring.datasource.password=8aTF1lg7yUH3skLe

# Configurações do Hibernate para sincronizar a tabela na nuvem
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true